### ISSUE TITLE
Create a task to manage heartbit

### ISSUE THREAD

**Issue by PFrank1990** [JBLSteeve/i2cExt#3]
Create a slow task (~1 second) that will manage heartbit of all registrered cards.
Use manageHbeat from CARDS class.

- [x] Create task
- [x] Check safe call between task (if necessary)
- [x] Call manageHbeat from each registered cards

**Comment by PFrank1990** [comment]
See commit 2193ba82c7f05c3ae4989abd78280f5d6ee55b6d

**Comment by JBLSteeve** [comment]
Issue is close and validated in develop branch
see commit d0ed40e662a9cb846746a9c0cf5e270b0cdebcab
